### PR TITLE
Allow access from outside

### PR DESCRIPTION
**Pull request by jcuerdo**
Allow access from outside

### CODE REVIEW

**Comment by mike61988** [comment]
Hi, 

Can you please provide a small explanation for step by step guide - how to use this?

Thanks,

**Comment by jcuerdo** [comment]
Is to allow access to the database from a client like sequel pro. From your machine. Now you can only access from the docker container.

**Comment by mike61988** [comment]
Yes, I got it :), but what config do I need to use to connect to DB, such as connection method, hostname, username, etc?

Thanks,

**Comment by mike61988** [comment]
I will appreciate if you provide a step by step guide for that.

Many thanks

**Comment by jcuerdo** [comment]
Opps sorry:

host=localhost
db=m2
user=root
password=[EMPTY]

**Comment by mike61988** [comment]
hm, I actually did the same before asking you, and I got the following error:

image

image

Thanks,

**Comment by jcuerdo** [comment]
Try docker-compose up -d --build

**Comment by mike61988** [comment]
Unfortunately, the same issue :(.

Any additional steps or checks do I need to do prior to that?

**Comment by jcuerdo** [comment]
The thing is the Dokerfile is not coping the file m23_config/mysql/my.cnf into the container so is never used... I'll do in another PR

**Comment by mike61988** [comment]
Oh, yes, you are right, I forgot that it was deleted. I was using it in the older version like you may see below:
https://github.com/mike61988/magento2-dk/blob/nfs_old/m22_config/Dockerfile

I will add it and reopen the PR.

Many thanks

**Comment by mike61988** [comment]
It doesn't work for me with a "root" user but works with another created user which has the password as well.

Many thanks for your help! :)

**Comment by jcuerdo** [comment]
Happy to help ¡¡¡ :)

**Pull request merged**
